config/routes.rb
Rails.application.routes.draw do
  resources :repositories, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/repository.rb
class Repository < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController

  def index
    @repositories = []
    if params[:search]
      data = Faraday.get("https://api.github.com/search/repositories") do |r|
        r.params['q'] = params[:search]
        r.headers['Accept'] = 'application/vnd.github.v3+json'
      end
      body = JSON.parse(data.body)
      @repositories = body["items"]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GetStuffFromGithub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/repositories/index.html.erb
<%= form_tag repositories_path, method: 'get' do %>
  <%= text_field_tag :search %>
  <%= submit_tag "Search" %>
<% end %>

<% @repositories.each do |repo| %>
  <h3><%= link_to repo["name"], repo["html_url"] %></h3>
  <p>Author: <%= repo["owner"]["login"] %></p>
<% end %>